name: build-no-matrix
on: [pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: Setup amplpy modules
      run: |
        set -xv
        python -m pip install amplpy --upgrade
        python -m amplpy.modules install gurobi highs coin
        python -m amplpy.modules activate ${{ secrets.AMPL_UUID }}
    - name: Install amplpower
      run: |
        python -m pip install .
    - name: test
      env:
        TOXPYTHON: 'python3.11'
      run: tox -e py311 -v
  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: codecov/codecov-action@v3
      with:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
